helloworld/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('website.urls', namespace='website')),

    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import IndexTemplateView, CursoListView, \
    CursoUpdateView, CursoCreateView, CursoDeleteView, UsuarioCreateView, UsuarioListView, UsuarioUpdateView, UsuarioDeleteView
from django.urls import path

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /curso/cadastrar
    path('curso/cadastrar', CursoCreateView.as_view(), name="cadastra_curso"),

    # GET /curso
    path('cursos/', CursoListView.as_view(), name="lista_cursos"),

    # GET/POST /cursos/{pk}
    path('curso/<pk>', CursoUpdateView.as_view(), name="atualiza_curso"),

    # GET/POST /cursos/excluir/{pk}
    path('curso/excluir/<pk>', CursoDeleteView.as_view(), name="deleta_curso"),

    # GET /usuario/cadastrar
    path('usuarios/cadastrar', UsuarioCreateView.as_view(), name="cadastra_usuario"),

    # GET /usuario
    path('usuarios/', UsuarioListView.as_view(), name="lista_usuarios"),

     # GET/POST /usuarios/{pk}
    path('usuario/<pk>', UsuarioUpdateView.as_view(), name="atualiza_usuario"),

     # GET/POST /usuarios/excluir/{pk}
    path('usuarios/excluir/<pk>', UsuarioDeleteView.as_view(), name="deleta_usuario"),


]

helloworld/models.py
from django.db import models

class Curso(models.Model):
    #o nome do curso deve ser único, não se repete
    nome = models.CharField(max_length=100, help_text="Digite o nome do curso", unique=True)    
    universidade = models.CharField(max_length=100, help_text='Digite a Universidade do curso')
    #Os campos nao podem ficar em branco ou ser nulos
    null = False
    blank = False

class Disciplina(models.Model):
    #o nome da disciplina deve ser único, não se repete
    nome = models.CharField(max_length=100, help_text='Digite o nome da disciplina', unique=True)
    null = False
    blank = False

class Usuario(models.Model):
    nome = models.CharField(max_length=100, help_text='Digite o nome completo')
    #podem existir 2 usuarios com mesmo nome, mas o e-mail é único 
    email = models.EmailField(help_text='Digite o email do usuário', unique=True)
    #data_criacao = models.DateTimeField()
    #universidade = Curso.universidade
    #cursando = Curso
    #Os campos nao podem ficar em branco ou ser nulos
    null = False
    blank = False

class Aluno(Usuario):
    curso = Curso


class Professor(Usuario):
    nivel = models.CharField(max_length=5, help_text='Digite o nível')
    #Os campos nao podem ficar em branco ou ser nulos
    null = False
    blank = False

class Comentario(models.Model):
    autor = Usuario
    data_criacao = models.DateTimeField()
    texto = models.CharField(max_length=1000, help_text='Digite sua resposta de no máximo 1000 caracteres')
    #Os campos nao podem ficar em branco ou ser nulos
    null = False
    blank = False

class Topico(models.Model):
    nome = models.CharField(max_length=100, help_text='Digite o nome do tópico', unique=True)
    data_criacao = models.DateTimeField()
    autor = Usuario
    #Os campos nao podem ficar em branco ou ser nulos
    null = False
    blank = False

objetos = models.Manager()

website/forms.py
from helloworld.models import Curso
from helloworld.models import Usuario
from django import forms


# FORMULÁRIO DE INCLUSÃO DE CURSOS
# -------------------------------------------

class InsereCursoForm(forms.ModelForm):

    class Meta:
        # Modelo base
        model = Curso

        # Campos que estarão no form
        fields = [
            'nome',
            'universidade'           
        ]


# FORMULÁRIO DE INCLUSÃO DE USUARIOS
# -------------------------------------------

class InsereUsuarioForm(forms.ModelForm):

    class Meta:
        # Modelo base
        model = Usuario

        # Campos que estarão no form
        fields = [
            'nome',
            'email', 
        
        ]

website/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from helloworld.models import Curso
from helloworld.models import Usuario
from website.forms import InsereCursoForm
from website.forms import InsereUsuarioForm

# PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


# LISTA DE CURSOS
# ----------------------------------------------

class CursoListView(ListView):
    template_name = "website/lista.html"
    model = Curso
    context_object_name = "cursos"


# CADASTRAMENTO DE CURSOS
# ----------------------------------------------

class CursoCreateView(CreateView):
    template_name = "website/cria.html"
    model = Curso
    form_class = InsereCursoForm
    success_url = reverse_lazy("website:lista_cursos")


# ATUALIZAÇÃO DE CURSOS
# ----------------------------------------------

class CursoUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Curso
    fields = '__all__'
    context_object_name = 'curso'
    success_url = reverse_lazy("website:lista_cursos")


# EXCLUSÃO DE CURSOS
# ----------------------------------------------

class CursoDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Curso
    context_object_name = 'curso'
    success_url = reverse_lazy("website:lista_cursos")


# LISTA DE USUARIOS
# ----------------------------------------------

class UsuarioListView(ListView):
    template_name = "website/lista_usuarios.html"
    model = Usuario
    context_object_name = "usuarios"



# CADASTRAMENTO DE USUARIOS
# ----------------------------------------------

class UsuarioCreateView(CreateView):
    template_name = "website/cria_usuario.html"
    model = Usuario
    form_class = InsereUsuarioForm
    success_url = reverse_lazy("website:lista_usuarios")



# ATUALIZAÇÃO DE USUARIOS
# ----------------------------------------------

class UsuarioUpdateView(UpdateView):
    template_name = "website/atualiza_usuario.html"
    model = Usuario
    fields = '__all__'
    context_object_name = 'usuario'
    success_url = reverse_lazy("website:lista_usuarios")



    # EXCLUSÃO DE USUARIOS
# ----------------------------------------------

class UsuarioDeleteView(DeleteView):
    template_name = "website/exclui_usuario.html"
    model = Usuario
    context_object_name = 'usuario'
    success_url = reverse_lazy("website:lista_usuarios")

website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Fórum Moodle{% endblock %}</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'website/img/favicon.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'website/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'website/css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'website:index' %}">
              <img src="{% static 'website/img/favicon.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button" 
                data-toggle="collapse" data-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'website:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'website:lista_cursos' %}">Cursos</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Hora: </b>{% tempo_atual %}</a>
                    </li>
                </ul>
            </div>
        </nav>
        
        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'website/js/jquery.min.js' %}"></script>
        <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'website/js/scripts.js' %}"></script>
    </body>
</html>

website/templates/website/atualiza.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Curso{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Cursos</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Universidade -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">universidade</span>
              </div>
              {% render_field form.universidade class+="form-control" %}
            </div>

            
            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_cursos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/atualiza_usuario.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Usuario{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Cursos</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            

            
            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_cursos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/cria.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Cursos{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Cursos</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Curso</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Universidade -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">universidade</span>
              </div>
              {% render_field form.universidade class+="form-control" %}
            </div>

            <hr>
            <div class="text-right">
              <a href="{% url 'website:lista_cursos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/cria_usuario.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Usuarios{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Usuario</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Usuario</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>
            
            <!-- Email -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">email</span>
              </div>
              {% render_field form.email class+="form-control" %}
            </div>

            
           

            <hr>
            <div class="text-right">
              <a href="{% url 'website:lista_usuarios' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/exclui.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Cursos</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o curso <b>{{ curso.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_cursos' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/exclui_usuario.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Usuarios</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o usuario <b>{{ curso.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_usuarios' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/index.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Curso</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Curso</code>.
          </p>
          <a href="{% url 'website:cadastra_curso' %}"
             class="btn btn-primary">
            Novo Curso
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Cursos</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Cursos</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_cursos' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Usuario</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Usuario</code>.
          </p>
          <a href="{% url 'website:cadastra_usuario' %}"
             class="btn btn-primary">
            Novo Usuario
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Usuario</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Usuarios</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_usuarios' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/lista.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Cursos{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Cursos</h5>

          {% if cursos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Cursos</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">nome</th>
                <th scope="col">universidade</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for curso in cursos %}
                <tr>
                  <th scope="row">{{ curso.nome|primeira_letra }}</th>
                  <td>{{ curso.nome }}</td>
                  <td>{{ curso.universidade }}</td>
                  <td class="text-center">
                    <a href="{% url 'website:atualiza_curso' pk=curso.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'website:deleta_curso' pk=curso.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Curso</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_curso' %}" class="btn btn-primary">
              Cadastrar Curso
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/lista_usuarios.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Usuarios{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Usuarios</h5>

          {% if usuarios|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Usuarios</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">nome</th>
                
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for usuario in usuarios %}
                <tr>
                  <th scope="row">{{ usuario.nome|primeira_letra }}</th>
                  <td>{{ usuario.nome }}</td>
                  <td>{{ usuario.email }}</td>
                 
                  <td class="text-center">
                    <a href="{% url 'website:atualiza_usuario' pk=usuario.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'website:deleta_usuario' pk=usuario.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Usuario</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_usuario' %}" class="btn btn-primary">
              Cadastrar Usuario
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}